<!DOCTYPE html>
<html>
<head>
    <title>Books Report</title>
    <meta charset="utf-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
        }
        .report-info {
            margin-bottom: 20px;
            font-size: 11px;
        }
        .report-info .filters {
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            color: #666;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Books Report</h1>
        <div class="report-info">
            Generated on: {{ $generated_at }}
            @if(array_filter($filters))
            <div class="filters">
                Filters applied:
                @if($filters['search'])
                    <strong>Search:</strong> "{{ $filters['search'] }}"
                @endif
                @if($filters['status'])
                    <strong>Status:</strong> {{ ucfirst($filters['status']) }}
                @endif
                @if($filters['genre'])
                    <strong>Genre:</strong> {{ $filters['genre'] }}
                @endif
            </div>
            @endif
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Genre</th>
                <th class="text-right">Price</th>
                <th>Status</th>
                <th class="text-right">Sales</th>
                <th class="text-right">Revenue</th>
                <th>Submitted</th>
            </tr>
        </thead>
        <tbody>
            @forelse($books as $book)
                @php
                    $salesCount = $book->walletTransactions->where('type', 'sale')->count();
                    $revenue = $book->walletTransactions->where('type', 'sale')->sum('amount');
                @endphp
                <tr>
                    <td>{{ $book->title }}</td>
                    <td>{{ $book->user->name }}</td>
                    <td>{{ $book->genre }}</td>
                    <td class="text-right">₦{{ number_format($book->price, 2) }}</td>
                    <td>
                        @if($book->status === 'pending')
                            <span style="color: #ffc107;">Pending</span>
                        @elseif($book->status === 'accepted')
                            <span style="color: #28a745;">Published</span>
                        @elseif($book->status === 'rejected')
                            <span style="color: #dc3545;">Rejected</span>
                        @elseif($book->status === 'stocked')
                            <span style="color: #17a2b8;">Stocked</span>
                        @endif
                    </td>
                    <td class="text-right">{{ $salesCount }}</td>
                    <td class="text-right">₦{{ number_format($revenue, 2) }}</td>
                    <td>{{ $book->created_at->format('M d, Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" class="text-center">No books found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Total Books: {{ $books->count() }} | Report generated by Admin Panel
    </div>
</body>
</html>