<!DOCTYPE html>
<html>
<head>
    <title>Payouts Report</title>
    <meta charset="utf-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
        }
        .report-info {
            margin-bottom: 20px;
            font-size: 11px;
        }
        .report-info .filters {
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            color: #666;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payouts Report</h1>
        <div class="report-info">
            Generated on: {{ $generated_at }}
            @if(array_filter($filters))
            <div class="filters">
                Filters applied:
                @if($filters['search'])
                    <strong>Search:</strong> "{{ $filters['search'] }}"
                @endif
                @if($filters['status'])
                    <strong>Status:</strong> {{ ucfirst($filters['status']) }}
                @endif
                @if($filters['amount_min'])
                    <strong>Min Amount:</strong> ₦{{ number_format($filters['amount_min'], 2) }}
                @endif
                @if($filters['amount_max'])
                    <strong>Max Amount:</strong> ₦{{ number_format($filters['amount_max'], 2) }}
                @endif
            </div>
            @endif
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Author</th>
                <th>Email</th>
                <th class="text-right">Amount Requested</th>
                <th>Status</th>
                <th>Payment Method</th>
                <th>Requested Date</th>
                <th>Processed Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payouts as $payout)
                <tr>
                    <td>{{ $payout->user->name }}</td>
                    <td>{{ $payout->user->email }}</td>
                    <td class="text-right">₦{{ number_format($payout->amount_requested, 2) }}</td>
                    <td>
                        @if($payout->status === 'pending')
                            <span style="color: #ffc107;">Pending</span>
                        @elseif($payout->status === 'approved')
                            <span style="color: #28a745;">Approved</span>
                        @elseif($payout->status === 'denied')
                            <span style="color: #dc3545;">Denied</span>
                        @endif
                    </td>
                    <td>{{ ucfirst($payout->payment_method) }}</td>
                    <td>{{ $payout->created_at->format('M d, Y H:i') }}</td>
                    <td>{{ $payout->processed_at ? $payout->processed_at->format('M d, Y H:i') : 'Not processed' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" class="text-center">No payouts found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Total Payouts: {{ $payouts->count() }} | Report generated by Admin Panel
    </div>
</body>
</html>