<!DOCTYPE html>
<html>
<head>
    <title>Users Report</title>
    <meta charset="utf-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
        }
        .report-info {
            margin-bottom: 20px;
            font-size: 11px;
        }
        .report-info .filters {
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Users Report</h1>
        <div class="report-info">
            Generated on: {{ $generated_at }}
            @if(array_filter($filters))
            <div class="filters">
                Filters applied:
                @if($filters['search'])
                    <strong>Search:</strong> "{{ $filters['search'] }}"
                @endif
                @if($filters['role'])
                    <strong>Role:</strong> {{ ucfirst($filters['role']) }}
                @endif
                @if($filters['status'])
                    <strong>Status:</strong> {{ ucfirst($filters['status']) }}
                @endif
            </div>
            @endif
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role(s)</th>
                <th>Status</th>
                <th>Joined At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $user)
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                        @foreach($user->roles as $role)
                            {{ ucfirst($role->name) }}@if(!$loop->last), @endif
                        @endforeach
                    </td>
                    <td>
                        @if($user->email_verified_at)
                            <span style="color: #28a745;">Verified</span>
                        @else
                            <span style="color: #ffc107;">Unverified</span>
                        @endif
                    </td>
                    <td>{{ $user->created_at->format('M d, Y H:i') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center;">No users found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Total Users: {{ $users->count() }} | Report generated by Admin Panel
    </div>
</body>
</html>